-- drop table `data_raw`;
CREATE TABLE `solvency_data`.`data_raw` (
  `id` INT NOT NULL auto_increment,
  `资产识别` varchar(255) not null,
  `资产简称` varchar(255) not null,
  `资产全称` varchar(255) not null,
  `资产大类` varchar(255) not null,
  `资产类型` varchar(255) not null,
  `产品代码` varchar(255) ,
  `交易对手` varchar(255) not null,
  `持有份数` double ,
  `购买成本` double not null,
  `认可价值` double not null,
  `应收利息` double ,
  `应收股利` double ,
  `账户` varchar(255) not null,
  `表层资产简称` varchar(255) ,
  `表层资产全称` varchar(255) ,
  `表层资产产品代码` varchar(255) ,
  `表层资产大类` varchar(255) ,
  `表层资产类型` varchar(255) ,
  `交易层级` int ,
  `表层资产交易对手` varchar(255) ,
  `表层资产购买成本` double ,
  `表层资产认可价值` double ,
  `表层资产应收利息` double ,
  `表层资产起息日` date ,
  `表层资产到期日` date ,
  `表层资产信用评级` varchar(255) ,
  `是否为沪深300成分股` varchar(255) ,
  `持股比例` double ,
  `是否带有强制转换为普通股或减记条款` varchar(255) ,
  `发行机构类型` varchar(255) ,
  `发行银行类型` varchar(255) ,
  `发行银行资本充足率` double ,
  `发行银行一级资本充足率` double ,
  `发行银行 核心一级 资本充足率` double ,
  `发行保险公司综合偿付能力充足率` double ,
  `发行保险公司核心偿付能力充足率` double ,
  `是否在公开市场交易` varchar(255) ,
  `投资对象性质` varchar(255) ,
  `减值前账面价值` double ,
  `套期保值组合` varchar(255) ,
  `是否满足会计准则规定的套期有效性要求` varchar(255) ,
  `套期有效性` double ,
  `套期期限` double ,
  `所在城市` varchar(255) ,
  `投资时间` date ,
  `计量属性` varchar(255) ,
  `账面价值` double ,
  `所在国家（地区）` varchar(255) ,
  `存款银行账户号` varchar(255) ,
  `存款银行类型` varchar(255) ,
  `银行资本充足率` double ,
  `剩余年限` double ,
  `信用评级` varchar(255) ,
  `修正久期` double ,
  `是否为支持碳减排项目的绿色债券` varchar(255) ,
  `资产风险分类等级` varchar(255) ,
  `再保分入人类型` varchar(255) ,
  `再保分入独立法人地区` varchar(255) ,
  `偿付能力` double ,
  `各级偿付能力是否达到监管要求` varchar(255) ,
  `再保公司评级` varchar(255) ,
  `有无担保措施` varchar(255) ,
  `地区是否获得偿付能力等效资格` varchar(255) ,
  `是否是享受各级政府保费补贴的业务` varchar(255) ,
  `账龄` varchar(255) ,
  `账户类别` varchar(255) ,
  `资产五大类分类` varchar(255) not null,
    PRIMARY KEY (`id`));

--     
-- CREATE TABLE `solvency_datadata_complex_raw`.`data_complex_raw` (
--   `id` INT NOT NULL auto_increment,
--   `资产识别` varchar(255) not null,
--   `账户` varchar(255) not null,
--   `表层资产简称` varchar(255) ,
--   `表层资产全称` varchar(255) ,
--   `表层资产产品代码` varchar(255) ,
--   `表层资产大类` varchar(255) ,
--   `表层资产类型` varchar(255) ,
--   `交易层级` int ,
--   `表层资产交易对手` varchar(255) ,
--   `表层资产购买成本` double ,
--   `表层资产认可价值` double ,
--   `表层资产应收利息` double ,
--   `表层资产起息日` date ,
--   `表层资产到期日` date ,
--   `表层资产信用评级` varchar(255) ,
--   `资产五大类分类` varchar(255) not null,
--     PRIMARY KEY (`id`));